### ISSUE TITLE
Sourcemap functionality

### ISSUE THREAD

**Issue by paulirish** [appsforartists/ambidex#15]
`"devtool" : "source-map"`

This one is better than the other possibilities, so it keeps the large sourcemap files out of the original jsx.js source.

I tossed it into the end of of `function getSettings` in `createWebpackSettings.js` but yeah some `ENABLE_SOURCE_MAPS` flag would be better. :)

**Comment by appsforartists** [comment]
Thanks @paulirish!

**Comment by appsforartists** [comment]
For some reason, when I tried originally, it didn't seem to work.  Just tried it again, and got it working.  It'll be available in the next version as `ENABLE_SOURCE_MAPS`.

Thanks again for your help!
