### ISSUE TITLE
Inline css

### ISSUE THREAD

**Issue by tyler-waitt** [appsforartists/ambidex#18]
Do you have any ideas of how you're going to go about implementing inline CSS?  Just curious!

**Comment by appsforartists** [comment]
I'm away from my desk right now, but I just open sourced some samples.  Look at https://github.com/appsforartists/gravel and tell me if it's helpful. :smiley:

**Comment by appsforartists** [comment]
I should be shipping beta 3 with inline style support tomorrow.

**Comment by tyler-waitt** [comment]
Cool!  Thanks.  Yes, it's very helpful.  Along with this repo as well!

**Comment by appsforartists** [comment]
Cool.  Beta 3 is shipped (though I still need to update [the example](https://github.com/appsforartists/ambidex-example--bike-index/)).  Sounds like you got what you need, so I'm closing this issue.

**Comment by appsforartists** [comment]
Beta 3 also includes a [default stylesheet](https://github.com/appsforartists/ambidex/blob/iojs/src/defaults/styles/react-native.css) that matches the [React Native defaults](https://github.com/facebook/css-layout/blob/ecc61dae85407148c3fb0077e16bb718592e4e8d/README.md#default-values).
