### ISSUE TITLE
Resolving React Routers redirects in the server

### ISSUE THREAD

**Issue by sebas5384** [appsforartists/ambidex#20]
Building an app with auth polices, we had a need to redirect to the login page, but, in order to know if the user is logged in or not, I had to use my service's instance lib.
I'm using the @bobpace [branch](https://github.com/bobpace/react-router/tree/transitionContext) for adding some context data in the willTransition hooks.

But, the problem is that I can't redirect the response from the onAbort() function, example:
https://github.com/TallerWebSolutions/ambidex/blob/transition-to-context/src/Ambidex.server.js#L379-L398

I tried some things like:

```
connection.redirect(stack);
```

then....

```
connection.redirect(stack);
return connection.call(stack);
```

nope...

```
resolve(connection);
```

errors everywhere....

I'm a little lost here, some help?

**Comment by bobpace** [comment]
May not be the same solution for you, but my onAbort I use with fluxible app looks like this:

```
    options.onAbort = function serverSideAbort(abortReason, location) {
      if (abortReason instanceof Cancellation) {
        return;
      }
      else if (abortReason instanceof Redirect) {
        var path = this.makePath(abortReason.to, abortReason.params, abortReason.query);
        res.redirect(path);
      }
    };
```

**Comment by sebas5384** [comment]
This issue was resolved, I'll be back with the changes I had to make to make the react-router's onAbort() event interacts with the response of mach.

The problem was that I had to resolve() or reject() the promises.

Thanks for the help @bobpace !

**Comment by appsforartists** [comment]
Glad you got it sorted.  :smiley:

**Comment by sebas5384** [comment]
Here's the commit with the solution:
https://github.com/TallerWebSolutions/ambidex/commit/8487bd00172b8f366c0253a3a84fa777e487491c
