### ISSUE TITLE
How do you handle server side global singletons ?

### ISSUE THREAD

**Issue by jnak** [appsforartists/ambidex#5]
Hey Brenton, 

I was also working on a similar idea :) I think you didn't really answer the question the first guy asked at the conf. 

I believe he meant that app globals like stores need to be encapsulated while rendering on the server because the server needs to handle concurrent requests. How are you dealing with this issue  ?

Thanks!
J

**Comment by appsforartists** [comment]
Questions like this are probably better served in the [chat room](https://gitter.im/appsforartists/Ambidex?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) than in the issue tracker, but here it goes:

Reflux is instantiated [for every request on the server](https://github.com/appsforartists/ambidex/blob/master/src/Ambidex.server.js#L410-428), but only [once per session on the client](https://github.com/appsforartists/ambidex/blob/master/src/render.client.js#L26-45).  The wrapper that [makes Reflux instantiable is on GitHub here](https://github.com/appsforartists/isomorphic-reflux).

**Comment by jnak** [comment]
Didn't know about gitter. Thanks for the answer!
