### ISSUE TITLE
Peer Dependencies are Being Deprecated

### ISSUE THREAD

**Issue by knpwrs** [appsforartists/ambidex#8]
See npm/npm#6565.

**Comment by appsforartists** [comment]
> To be clear, peerDependencies aren't going away. The problem of keeping plugins versioned consistently with the thing to which they plug in is still a big one for many projects. The problem is that peerDependency handling often causes more problems than it solves, and has a bad habit of putting developers right back into the dependency hell that npm tries to help you escape. This is our next step to make things work more smoothly and less invasively.

Doesn't sound like we're affected.  Thanks for the tip though.

**Comment by knpwrs** [comment]
Yeah, I was in the same boat as your comment on that issue and just went with what the title said.
